### ISSUE TITLE
Can you supply your dataset?

### ISSUE THREAD

**Issue by qiaoyu2015** [drewlinsley/hgru_share#1]
Can you supply your dataset? I have researched your code, but I have some doubt about the dataset structure. Can you supply your dataset link for me to help my research? Thank you very much.

**Comment by drewlinsley** [comment]
Hi, Yes I can do this. Hopefully I will have a link up in the next week.

Drew

**Comment by qiaoyu2015** [comment]
> Hi, Yes I can do this. Hopefully I will have a link up in the next week.
> 
> Drew

Thank you very much.

**Comment by drewlinsley** [comment]
So sorry about the delay on this:
[Pathfinder 6](https://drive.google.com/file/d/13y1cclbbyqm3pqCtxX0D5F_rBo9s2bKb/view?usp=sharing)
[Pathfinder 6](https://drive.google.com/file/d/1ZrZvfWcl1OvUQWxnkQxOdyantpA7NTR8/view?usp=sharing)
[Pathfinder 14](https://drive.google.com/file/d/1Qju_FmGQwoOeIZ-Tj8csmniBEG5YqdlN/view?usp=sharing)

**Comment by maximzubkov** [comment]
Hello!
I came to this issue when I was searching for a pathfinder dataset. Could you please update the links to dataset files, since they are currently unavailable
