### ISSUE TITLE
Could you please provide links to dataset?

### ISSUE THREAD

**Issue by maximzubkov** [drewlinsley/hgru_share#2]
Hello!
I am doing my research related to understanding long-term dependencies using transformer-based models. I came to this repo when I was searching for the pathfinder dataset. Could you please provide the links to dataset files, since they are currently unavailable?

**Comment by drewlinsley** [comment]
Hi @maximzubkov I'm zipping the files and uploading to a new host as we speak. Stay tuned.

**Comment by drewlinsley** [comment]
PF14 link is updated. https://drive.google.com/file/d/1Qju_FmGQwoOeIZ-Tj8csmniBEG5YqdlN/view?usp=sharing
PF6 link is updated. https://drive.google.com/file/d/13y1cclbbyqm3pqCtxX0D5F_rBo9s2bKb/view?usp=sharing
PF9 link is updated. https://drive.google.com/file/d/1ZrZvfWcl1OvUQWxnkQxOdyantpA7NTR8/view?usp=sharing

**Comment by maximzubkov** [comment]
Thank you!
